calories<-read.csv("C:/Users/admin/Desktop/Datascience/Linear Regression/calories_consumed.csv")
install.packages("lattice")
library(lattice)
dotplot(calories$Weight.gained..grams,main="Dot plot for Weight.gained..grams circulations",col="dodgerblue4")
dotplot(calories$Calories.Consumed,main="Dot plot for Calories.Consumed circulations",col="dodgerblue4")
boxplot(calories$Weight.gained..grams,col="dodgerblue4")
boxplot(calories$Calories.Consumed,col="dodgerblue4")
colnames(calories)
model <- lm(Weight.gained..grams.~Calories.Consumed,data=calories)
summary(model)
