Emp_data<-read.csv("C:/Users/admin/Desktop/Datascience/Linear Regression/emp_data.csv")
install.packages("lattice")
library(lattice)
dotplot(Emp_data$Salary_hike,main="Dot plot for Salary_hike circulations",col="dodgerblue4")
dotplot(Emp_data$Salary,main="Dot plot for Churn_out_rate circulations",col="dodgerblue4")
boxplot(Emp_data$Salary_hike,col="dodgerblue4")
boxplot(Emp_data$Churn_out_rate,col="dodgerblue4")
colnames(Emp_data)
model <- lm(Churn_out_rate~Salary_hike,data=Emp_data)
summary(model)
