Salary_hike<-read.csv("C:/Users/admin/Desktop/Datascience/Linear Regression/Salary_data.csv")
install.packages("lattice")
library(lattice)
dotplot(Salary_hike$YearsExperience,main="Dot plot for YearsExperience circulations",col="dodgerblue4")
dotplot(Salary_hike$Salary,main="Dot plot for Salary circulations",col="dodgerblue4")
boxplot(Salary_hike$YearsExperience,col="dodgerblue4")
boxplot(Salary_hike$Salary,col="dodgerblue4")
colnames(Salary_hike)
model <- lm(Salary~YearsExperience,data=Salary_hike)
summary(model)
